# Generated by Django 4.0 on 2023-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='number_of_slides',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
