# Generated by Django 4.0 on 2023-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flashcard_number_of_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='read_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
